name: Esy Pipeline (melange-basic-template)

on:
  pull_request:
  push:
    branches:
     - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test

    strategy:
      matrix:
        # https://github.com/melange-re/melange/issues/165
        system: [ ubuntu ] # macos # windows

    runs-on: ${{ matrix.system }}-latest

    steps:
      - uses: actions/setup-node@v3
        if: ${{ matrix.system != 'macos-arm64' }}
        with:
          node-version: 18

      - name: Install esy
        if: ${{ matrix.system != 'macos-arm64' }}
        run: npm install -g esy@next

      - name: Cache Esy artifacts
        id: cache-esy
        uses: actions/cache@v3
        env:
          cache-name: cache-esy
        with:
          path: ~/.esy
          key: ${{ matrix.system }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ matrix.system }}-build-${{ env.cache-name }}-
            ${{ matrix.system }}-build-
            ${{ matrix.system }}-

      - name: Clone basic template
        if: ${{ matrix.system == 'ubuntu' }}
        run: |
          git clone https://github.com/melange-re/melange-basic-template.git
          cd melange-basic-template

      - name: Remove esy.lock in template
        if: ${{ matrix.system == 'ubuntu' }}
        working-directory: melange-basic-template
        run: rm -rf esy.lock

      - name: Add resolutions to template esy.json
        if: ${{ matrix.system == 'ubuntu' }}
        working-directory: melange-basic-template
        run: |
          sed -i 's@"installConfig"@"resolutions": { "\@opam/reactjs-jsx-ppx": "reasonml/reason-react:reactjs-jsx-ppx.opam#97d31755c8d24fab13d6b60a3980505c917c1244","\@opam/melange": "melange-re/melange:melange.opam#'"$GITHUB_SHA"'", "\@opam/reason-react": "reasonml/reason-react:reason-react.opam#97d31755c8d24fab13d6b60a3980505c917c1244"},"installConfig"@' esy.json
      - name: Build basic template
        if: ${{ matrix.system == 'ubuntu' }}
        working-directory: melange-basic-template
        run: |
          cat esy.json
          esy install
          npm install --legacy-peer-deps
          esy
          npm run bundle
