name: Esy Pipeline (melange-basic-template)

on:
  pull_request:
  push:
    branches:
     - main

jobs:
  build:
    name: Build and test

    strategy:
      matrix:
        # https://github.com/melange-re/melange/issues/165
        system: [ ubuntu, macos ] # windows

    runs-on: ${{ matrix.system }}-latest

    steps:
      - uses: actions/setup-node@v3
        if: ${{ matrix.system != 'macos-arm64' }}
        with:
          node-version: 18

      - name: Install esy
        if: ${{ matrix.system != 'macos-arm64' }}
        run: npm install -g esy@next

      - name: Clone basic template
        if: ${{ matrix.system == 'ubuntu' }}
        run: git clone https://github.com/melange-re/melange-basic-template.git

      - name: Remove esy.lock in template
        if: ${{ matrix.system == 'ubuntu' }}
        working-directory: melange-basic-template
        run: rm -rf esy.lock

      - name: Add resolutions to template esy.json
        if: ${{ matrix.system == 'ubuntu' }}
        working-directory: melange-basic-template
        run: |
          sed -i 's@"installConfig"@"resolutions": { "\@opam/melange": "melange-re/melange:melange.opam#'"$GITHUB_SHA"'", "\@opam/mel": "melange-re/melange:mel.opam#'"$GITHUB_SHA"'"},"installConfig"@' esy.json

      - name: Build basic template
        if: ${{ matrix.system == 'ubuntu' }}
        working-directory: melange-basic-template
        run: |
          cat esy.json
          esy install
          npm install
          esy
          npm run bundle
