name: Esy Pipeline

on:
  pull_request:
  push:
    branches:
      - fork

jobs:
  build:
    name: Build and test

    strategy:
      matrix:
        # https://github.com/melange-re/melange/issues/165
        system: [ ubuntu, macos] # windows,

    runs-on: ${{ matrix.system }}-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: melange

      - uses: actions/setup-node@v3
        if: ${{ matrix.system != 'macos-arm64' }}
        with:
          node-version: 14

      - name: Install esy
        if: ${{ matrix.system != 'macos-arm64' }}
        run: npm install -g esy@next

      - uses: esy/github-action@master
        with:
          cache-key: ${{ hashFiles('melange/esy.lock/index.json') }}
          manifest: melange/esy.json

      - name: Run tests.
        if: ${{ matrix.system != 'windows' }}
        working-directory: melange
        run: esy test

      - name: Install ocaml-tree
        if: ${{ matrix.system == 'ubuntu' }}
        working-directory: melange/ocaml-tree
        run: npm install

      - name: Clone basic template
        if: ${{ matrix.system == 'ubuntu' }}
        run: git clone -b directory-targets https://github.com/jchavarri/melange-basic-template.git

      - name: Remove esy.lock in template
        if: ${{ matrix.system == 'ubuntu' }}
        working-directory: melange-basic-template
        run: rm -rf esy.lock

      - name: Replace dune dep in template esy.json
        if: ${{ matrix.system == 'ubuntu' }}
        working-directory: melange-basic-template
        run: |
          sed -i 's/"\@opam\/dune": ".*"/"\@opam\/dune": "*"/' esy.json

      - name: Replace melange dep in template esy.json
        if: ${{ matrix.system == 'ubuntu' }}
        working-directory: melange-basic-template
        run: |
          sed -i 's/"melange": "melange-re\/melange"/"melange": "*"/' esy.json

      - name: Add resolutions to template esy.json
        if: ${{ matrix.system == 'ubuntu' }}
        working-directory: melange-basic-template
        run: |
          sed -i 's/"installConfig": { "pnp": false }/"installConfig": { "pnp": false },"resolutions": { "melange": "link:..", "\@opam\/dune": "ocaml\/dune:dune.opam#72e8088"}/' esy.json

      - name: Build basic template
        if: ${{ matrix.system == 'ubuntu' }}
        working-directory: melange-basic-template
        run: |
          cat esy.json
          esy install
          npm install
          esy
          ls -la .
          tree -l 2 _build/
          npm run bundle
